version: '3.9'

volumes:
  db_data:
    driver: local

networks:
  agenda-net:
    driver: bridge
  rabbitmq_net:
    driver: bridge
  db_net:
    driver: bridge

services:
  web:
    build: ./web
    container_name: agenda-net-web
    volumes: 
      - ./web:/app
      - /app/node_modules
    ports:
      - "4200:8080"
    depends_on:
      - api
    networks:
      - agenda-net

  api:
    build: ./backend/AgendaNetApi
    container_name: agenda-net-api
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__AgendaNetDB: Server=agenda-net-db;User=agenda_net;Password=agenda_net;SslMode=None;Database=agenda_net_db
      ConnectionStrings__RabbitMQ: amqp://guest:guest@agenda-net-rabbitmq:5672
    restart: on-failure
    depends_on:
      - rabbitmq
      - db
    links: 
      - rabbitmq
    networks:
      - agenda-net
      - rabbitmq_net
  
  db:
    image: mysql:5.7
    container_name: agenda-net-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agenda_net_db
      MYSQL_USER: agenda_net
      MYSQL_PASSWORD: agenda_net
    ports:
      - "3306:3306"
    networks:
      - agenda-net
      - db_net

  phpmyadmin:
    image: phpmyadmin
    container_name: agenda-net-phpmyadmin
    restart: always
    links:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - db_net
    ports:
      - 8080:80
    depends_on:
      - db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: agenda-net-rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - rabbitmq_net