FROM mcr.microsoft.com/dotnet/sdk:6.0

WORKDIR /src

COPY . .

RUN dotnet restore

RUN dotnet build "AgendaNet.Api/AgendaNet.Api.csproj"

EXPOSE 5000
EXPOSE 80

ENTRYPOINT ["dotnet", "run", "--project", "AgendaNet.Api/AgendaNet.Api.csproj"]
